/*
 * cups_epilog.h
 *
 *  Created on: 19.09.2009
 *      Author: amir
 */

#ifndef CUPS_EPILOG_H_
#define CUPS_EPILOG_H_

/** Default for debug mode. */
#define DEBUG (1)

/** Number of bytes in the bitmap header. */
#define BITMAP_HEADER_NBYTES (54)

/** Basename for files generated by the program. */
#define FILE_BASENAME "epilog"

/** Number of characters allowable for a filename. */
#define FILENAME_NCHARS (128)

/** Maximum allowable hostname characters. */
#define HOSTNAME_NCHARS (1024)

/** Temporary directory to store files. */
#define TMP_DIRECTORY "/tmp"


int big_to_little_endian(uint8_t *position, int bytes);
void range_checks(void);
extern bool execute_ghostscript(char *filename_bitmap, char *filename_eps,
                                char *filename_vector,
                                char *bmp_mode, int resolution,
                                int height, int width);
extern bool generate_raster(printer_job pjob, laser_config lconf, FILE *bitmap_file);
extern bool generate_vector(printer_job pjob, laser_config lconf, FILE *vector_file);
extern bool generate_pjl(printer_job pjob, laser_config lconf, FILE *bitmap_file, FILE *vector_file);
extern bool ps_to_eps(FILE *ps_file, FILE *eps_file);
extern bool process_job_title_commands(printer_job pjob);
extern bool process_queue_options(laser_config *lconf, char *queue_options);


#endif
