#!bin/bash

#
# only $CHROOT and $MOUNTS are relevant to chrtsetup
#

ROOT="./test-data/chroot"
CHROOT=$ROOT/root

#from		to                      fstype  mount-options   do-chroot
MOUNTS=`echo -e "\
/dev            $CHROOT/dev             none    bind            false	\n\
none            /proc                   proc    defaults        true	\n\
none            /sys                    sysfs   defaults        true	\n\
none		/dev/pts                devpts  defaults        true	\n\
"`

