#ifndef CTRLCUT_H_
#define CTRLCUT_H_

/** Basename for files generated by the program. */
#define FILE_BASENAME "ctrl-cut"

/** Number of characters allowable for a filename. */
#define FILENAME_NCHARS (128)

/** Maximum allowable hostname characters. */
#define HOSTNAME_NCHARS (1024)

/** Temporary directory to store files. */
#define TMP_DIRECTORY "/tmp"

#define PRINTER_NAME "LaserCutter"

#endif /* CUPSPARSER_H_ */
