#ifndef EPILOGFILTER_H_
#define EPILOGFILTER_H_

/** Default for debug mode. */
#define DEBUG (1)

/** Number of bytes in the bitmap header. */
#define BITMAP_HEADER_NBYTES (54)

/** Basename for files generated by the program. */
#define FILE_BASENAME "epilog"

/** Number of characters allowable for a filename. */
#define FILENAME_NCHARS (128)

/** Maximum allowable hostname characters. */
#define HOSTNAME_NCHARS (1024)

/** Temporary directory to store files. */
#define TMP_DIRECTORY "/tmp"

#define PRINTER_NAME "LaserCutter"

#define GTKLP_CONF_DIR "/home/amir/dev/Epilog/gtklpconf/"

#endif /* CUPSPARSER_H_ */
